// <auto-generated />
namespace TPA.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImplementAttributeMetadata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImplementAttributeMetadata));
        
        string IMigrationMetadata.Id
        {
            get { return "201801282315524_ImplementAttributeMetadata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
