select * from AssemblyMetadatas
select * from NamespaceMetadatas
select * from TypeMetadatas
select * from Types_UsedAttributes
select * from AttributeMetadatas
select * from Types_ImplementedInterfaces	
select * from PropertyMetadatas
select * from MethodMetadatas
select * from FieldMetadatas
select * from Methods_UsedAttributes